name: build-windows
on: [push, pull_request]
jobs:
  check-lines:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check lines
      run: find "Content/" -type f -exec python3 Scripts/CheckLines.py {} +
  compile-cpp11:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check versions
      run: |
        g++ --version
    - name: Replace pragma once
      run: find "Content/C++/" -name "*.h" -exec python3 Scripts/ReplacePragmas.py {} +
    - name: Compile
      run: find "Content/C++/" -name "*.h" -exec Scripts/Compile.sh "g++ -std=c++11 -Wall -Wextra -pedantic-errors -Werror -fsyntax-only" {} +
  compile-cpp14:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check versions
      run: |
        g++ --version
    - name: Replace pragma once
      run: find "Content/C++/" -name "*.h" -exec python3 Scripts/ReplacePragmas.py {} +
    - name: Compile
      run: find "Content/C++/" -name "*.h" -exec Scripts/Compile.sh "g++ -std=c++14 -Wall -Wextra -pedantic-errors -Werror -fsyntax-only" {} +
  compile-cpp17:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check versions
      run: |
        g++ --version
    - name: Replace pragma once
      run: find "Content/C++/" -name "*.h" -exec python3 Scripts/ReplacePragmas.py {} +
    - name: Compile
      run: find "Content/C++/" -name "*.h" -exec Scripts/Compile.sh "g++ -std=c++17 -Wall -Wextra -pedantic-errors -Werror -fsyntax-only" {} +
  fuzz-tests-cpp:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check versions
      run: |
        g++ --version
    - name: Replace pragma once
      run: find "Content/C++/" -name "*.h" -exec python3 Scripts/ReplacePragmas.py {} +
    - name: Run fuzz tests
      run: find "Tests/C++/" -name "*FuzzTest.cpp" -exec Scripts/RunCppTests.sh {} +
  stress-tests-cpp:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check versions
      run: |
        g++ --version
    - name: Replace pragma once
      run: find "Content/C++/" -name "*.h" -exec python3 Scripts/ReplacePragmas.py {} +
    - name: Run stress tests
      run: find "Tests/C++/" -name "*StressTest.cpp" -exec Scripts/RunCppTests.sh {} +
