name: check lines
on: [push, pull_request]
jobs:
  check-line-endings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check line endings
      run: find -type f \( -iname \*.h -o -iname \*.java -o -iname \*.kt \) -exec python3 .github/CheckLineEndings.py {} +
  check-line-lengths:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check line lengths
      run: find -type f \( -iname \*.h -o -iname \*.java -o -iname \*.kt \) -exec python3 .github/CheckLineLengths.py {} +
